package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.commons.lang.math.NumberUtils;
import program.Connect;
import program.Language;
import program.PointsDB;
import program.StudentDB;

public class Points extends javax.swing.JDialog {
    private int points, choice;
    private String date;
    private String description;
    private String studentas;
    private Connect con;
    private PointsDB someone;
    private boolean entered = false;
    /**
     * Creates new form Points
     */
    public Points(java.awt.Frame parent, boolean modal, Connect info) {
        super(parent, modal);
        initComponents();
        con = info;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        data = new javax.swing.JTextField();
        pointsamount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        desc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add an Activity Points");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Description:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Date:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Number of points:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Student:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pointsamount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox1, 0, 265, Short.MAX_VALUE)
                    .addComponent(desc))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pointsamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void LanguageSettings(int enOrLt) {
        Language language = new Language();
        choice = enOrLt;
        if (enOrLt == 1) {
            jLabel1.setText(language.English[14]);
            jLabel2.setText(language.English[12]);
            jLabel3.setText(language.English[13]);
            jLabel4.setText(language.English[8]);
            jButton1.setText(language.English[15]);
        } else {
            jLabel1.setText(language.Lithuanian[14]);
            jLabel2.setText(language.Lithuanian[12]);
            jLabel3.setText(language.Lithuanian[13]);
            jLabel4.setText(language.Lithuanian[8]);
            jButton1.setText(language.Lithuanian[15]);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        someone = new PointsDB();
        studentas = jComboBox1.getSelectedItem().toString();
        someone.setStudent(studentas);
        description = desc.getText();
        if ((data.getText().matches("([0-9]{4})-([0-9]{2})-([0-9]{2})")) && !description.isEmpty() && NumberUtils.isNumber(pointsamount.getText())) {
            points = Integer.parseInt(pointsamount.getText());
            someone.setPoints(points);
            date = data.getText();
            someone.setDate(date);
            someone.setDescription(description);
            try {
                Connection conn;
                String driver = "net.ucanaccess.jdbc.UcanaccessDriver";
                try {
                    Class.forName(driver);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Points.class.getName()).log(Level.SEVERE, null, ex);
                }
                conn = DriverManager.getConnection("jdbc:ucanaccess://" + "Database.accdb");
                String sql = ("INSERT INTO Points (Student, Date, Points, Description) VALUES(?,?,?,?)");
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, studentas);
                st.setDate(2, java.sql.Date.valueOf(date));
                st.setInt(3, points);
                st.setString(4, description);
                st.execute();
            } catch (SQLException ex) {
                Logger.getLogger(Group.class.getName()).log(Level.SEVERE, null, ex);
            }
            entered = true;
            this.dispose();
        } else {
          if (choice == 1)
                JOptionPane.showMessageDialog(this, "You inputted wrong Date!\nYou must fill all fields!\nFormat should be yyyy-mm-dd", "Error", JOptionPane.ERROR_MESSAGE);
           else JOptionPane.showMessageDialog(this, "Jūs įvedėte neteisingą Datą!\nReikia užpildyti visus laukus!\nFormatas turi atrodyti yyyy-mm-dd", "Klaida", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
  
    public void showProperties (ArrayList <StudentDB> std) {
        String[] person = new String[std.size()];
        for (int i = 0; i < std.size(); i++)
            person[i] = std.get(i).getGroup() + " " + std.get(i).getName() + " " + std.get(i).getSurname();
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(person));
    }
    
    public boolean isEntered() {
        return entered;
    }

    public PointsDB getSomeone() {
        return someone;
    }
    /**
     * @param args the command line arguments
     */



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField data;
    private javax.swing.JTextField desc;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField pointsamount;
    // End of variables declaration//GEN-END:variables
}
